version: '3'

services:
  stockwebservice:
    build: ./
    image: minifarm/stockwebservice:0.1
    container_name: minifarm_stockwebservice
    domainname: domain.tld
    hostname: hostname
    ports:
    - "8080:8080"
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=1 -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      JDBC_URL: "jdbc:sqlserver://ip:port;database=database_name"
      JDBC_USERNAME: "username"
      JDBC_PASSWORD: "password"
      API_PASSWORD: "api_password"