version: '2.4'

services:
  stockwebservice:
    image: stockwebservice
    mem_limit: 2G
    memswap_limit: 4G
    cpus: 0.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
    - 8080:8080
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=1 -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      JDBC_USERNAME: ""
      JDBC_PASSWORD: ""
      API_PASSWORD: ""

# docker-compose build && docker-compose up